### ISSUE TITLE
No SFF support

### ISSUE THREAD

**Issue by Leont** [genoo/GenOO#11]
I'm surprised to see a toolkit for high throughput sequencing analysis that is not supporting the SFF format, several years ago I wrote Bio::SFF in the hope that people would use it for exactly this kind of purpose.

**Comment by mnsmar** [comment]
Thanks for reporting. We mostly try to implement the standard formats. SFF is a platform specific format so I don't see it coming in GenOO core at this point. It is probably best fit as a an extension module - similar to GenOOx-Sam-STAR.

**Comment by Leont** [comment]
Sounds reasonable :-)
